language:
  - cpp

os:
  - linux

dist:
  - bionic

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get -y install qt5-default

addons:
  apt:
    update: true
    
script:
  ./TestScripts/BuildProcess.sh
